# Generated by Django 4.1.7 on 2023-03-21 15:12

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('publication_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/')),
                ('category', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('document', 'Document'), ('music', 'Music'), ('other', 'Other')], default='other', max_length=40, verbose_name='File Category')),
                ('publication_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg', 'jpeg'])])),
                ('category', models.CharField(choices=[('airplane', 'Airplane'), ('automobile', 'Automobile'), ('bird', 'Bird'), ('cat', 'Cat'), ('deer', 'Deer'), ('dog', 'Dog'), ('frog', 'Frog'), ('horse', 'Horse'), ('ship', 'Ship'), ('truck', 'Truck')], default='other', max_length=40, verbose_name='Image Category')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
