# Generated by Django 4.1.7 on 2023-03-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mediauploadapp", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="category",
        ),
    ]
