# Generated by Django 4.1.7 on 2023-03-27 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediauploadapp', '0004_remove_file_author_id_alter_photo_file_delete_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(unique=True, upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg', 'jpeg', 'gif', 'eps', 'raw'])]),
        ),
    ]
