version: "3.7"

x-app: &default-app
  build:
    context: "."
  volumes:
    - .:/app
  restart: "unless-stopped"

services:
  web:
    <<: *default-app
    command: "python recognizer/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  tailwind:
    <<: *default-app
    command: "python recognizer/manage.py tailwind start"
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true