# Generated by Django 4.1.3 on 2022-11-20 13:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=600, verbose_name='Description'),
        ),
    ]
